# This is a basic workflow to help you get started with Actions

name: 检查更新

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 */3 * * *"
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - uses: RangHo/setup-arch@v1.2.1
        with:
          packages: python git

      - name: Create SSH key
        env:
          SUPER_SECRET: ${{ secrets.AUR_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SUPER_SECRET" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/*
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts

      - name: Run check version script
        shell: arch.sh {0}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          ./check_version.sh

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update from Github Action"

      - name: git push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
